// js/resumo-dados.js
//
// Conteúdo estático do Resumo de Assuntos do ENEM — lista de estudo
// fornecida pelo usuário, organizada por disciplina, mais uma seção de
// prioridade. Isto é material de referência (não vem da API ENEM.dev e não
// está vinculado a questões específicas).

export const CATEGORIAS = [
  {
    id: 'matematica',
    emoji: '🧮',
    nome: 'Matemática',
    topicos: [
      'Porcentagem',
      'Razão e proporção',
      'Regra de três',
      'Matemática financeira',
      'Estatística',
      'Média, mediana e moda',
      'Probabilidade',
      'Funções',
      'Função afim',
      'Função quadrática',
      'Geometria plana',
      'Áreas e perímetros',
      'Geometria espacial',
      'Volumes',
      'Análise de gráficos e tabelas',
      'Equações e sistemas',
      'Trigonometria',
    ],
  },
  {
    id: 'redacao',
    emoji: '✍️',
    nome: 'Redação',
    topicos: [
      'Estrutura da redação ENEM',
      'Introdução e tese',
      'Desenvolvimento argumentativo',
      'Repertório sociocultural',
      'Argumentação',
      'Coesão e coerência',
      'Conectivos',
      'Projeto de texto',
      'Proposta de intervenção',
      'Competências 1 a 5',
      'Temas sociais',
      'Educação',
      'Saúde',
      'Meio ambiente',
      'Tecnologia',
      'Desigualdade social',
      'Cidadania',
    ],
  },
  {
    id: 'linguagens',
    emoji: '📖',
    nome: 'Linguagens',
    topicos: [
      'Interpretação de texto',
      'Gêneros textuais',
      'Funções da linguagem',
      'Variação linguística',
      'Figuras de linguagem',
      'Intertextualidade',
      'Linguagem verbal e não verbal',
      'Argumentação',
      'Literatura e contexto histórico',
      'Modernismo',
      'Artes e cultura',
    ],
  },
  {
    id: 'geografia',
    emoji: '🌎',
    nome: 'Geografia',
    topicos: [
      'Globalização',
      'Geopolítica',
      'Urbanização',
      'Industrialização',
      'Agropecuária',
      'Meio ambiente',
      'Mudanças climáticas',
      'Energia',
      'População e migrações',
      'Questão agrária',
      'Geografia do Brasil',
    ],
  },
  {
    id: 'historia',
    emoji: '🏛️',
    nome: 'História',
    topicos: [
      'Brasil Colônia e escravidão',
      'Era Vargas',
      'Ditadura Militar',
      'República Velha',
      'Redemocratização',
      'Revolução Industrial',
      'Imperialismo',
      'Segunda Guerra Mundial',
      'Guerra Fria',
      'Revolução Francesa',
    ],
  },
  {
    id: 'filosofia',
    emoji: '🧠',
    nome: 'Filosofia',
    topicos: [
      'Ética',
      'Política e poder',
      'Teoria do conhecimento',
      'Platão e Aristóteles',
      'Maquiavel',
      'Hobbes, Locke e Rousseau',
      'Kant',
      'Marx',
      'Nietzsche',
    ],
  },
  {
    id: 'sociologia',
    emoji: '👥',
    nome: 'Sociologia',
    topicos: [
      'Cultura',
      'Desigualdade social',
      'Trabalho',
      'Estado e poder',
      'Cidadania',
      'Movimentos sociais',
      'Indústria cultural',
      'Marx, Durkheim e Weber',
    ],
  },
  {
    id: 'biologia',
    emoji: '🧬',
    nome: 'Biologia',
    topicos: [
      'Ecologia',
      'Cadeias e teias alimentares',
      'Ciclos biogeoquímicos',
      'Impactos ambientais',
      'Genética',
      'DNA e RNA',
      'Hereditariedade',
      'Evolução',
      'Fisiologia humana',
      'Sistema imunológico',
      'Citologia',
      'Metabolismo energético',
      'Biotecnologia',
      'Parasitologia',
    ],
  },
  {
    id: 'quimica',
    emoji: '⚗️',
    nome: 'Química',
    topicos: [
      'Estequiometria',
      'Soluções e concentração',
      'Química orgânica',
      'Funções orgânicas',
      'Reações orgânicas',
      'Petróleo e combustíveis',
      'Eletroquímica',
      'Pilhas',
      'Termoquímica',
      'Cinética química',
      'Equilíbrio químico',
      'Ácidos e bases',
      'pH e pOH',
      'Química ambiental',
    ],
  },
  {
    id: 'fisica',
    emoji: '⚡',
    nome: 'Física',
    topicos: [
      'Cinemática',
      'Leis de Newton',
      'Trabalho e energia',
      'Potência',
      'Hidrostática',
      'Calorimetria',
      'Termodinâmica',
      'Óptica',
      'Ondulatória',
      'Eletricidade',
      'Eletrodinâmica',
      'Circuitos elétricos',
      'Potência elétrica',
    ],
  },
];

export const PRIORIDADE = [
  {
    id: 'nivel1',
    nome: 'Nível 1 — dominar primeiro',
    topicos: [
      'Redação',
      'Interpretação de texto',
      'Porcentagem',
      'Razão, proporção e regra de três',
      'Estatística',
      'Geometria',
      'Funções',
      'Probabilidade',
      'Ecologia',
      'Genética',
      'Fisiologia humana',
      'Química orgânica',
      'Estequiometria',
      'Eletricidade',
      'Mecânica',
      'Globalização e geopolítica',
    ],
  },
  {
    id: 'nivel2',
    nome: 'Nível 2 — estudar depois',
    topicos: [
      'Matemática financeira',
      'Geometria espacial',
      'Trigonometria',
      'Brasil República',
      'Urbanização e industrialização',
      'Meio ambiente',
      'Filosofia política e ética',
      'Sociologia — trabalho e desigualdade',
      'Eletroquímica',
      'Termoquímica',
      'Ondulatória',
      'Termodinâmica',
    ],
  },
];
