// js/resumo-dados.js
//
// Conteúdo estático do Resumo de Assuntos do ENEM — cada tópico tem um
// nome e um resumo curto (conteúdo educacional de referência, escrito
// como material de apoio; não vem da API ENEM.dev e não está vinculado a
// questões específicas). A seção de Prioridade usa só os nomes (sem
// resumo próprio), já que vários itens combinam mais de um tópico da
// lista por disciplina.

export const CATEGORIAS = [
  {
    id: 'matematica',
    emoji: '🧮',
    nome: 'Matemática',
    topicos: [
      { nome: 'Porcentagem', resumo: 'Porcentagem é uma razão com denominador 100, indicada pelo símbolo %. No ENEM aparece em problemas de aumento/desconto (ex.: acréscimo de 20% = multiplicar por 1,20) e em leitura de gráficos e reportagens. Praticar a conversão entre fração, decimal e porcentagem agiliza a resolução.' },
      { nome: 'Razão e proporção', resumo: 'Razão é a comparação entre duas grandezas (a/b); proporção é a igualdade entre duas razões (a/b = c/d). A propriedade fundamental das proporções (produto dos meios = produto dos extremos) resolve boa parte das questões que envolvem escalas, misturas e divisão proporcional.' },
      { nome: 'Regra de três', resumo: 'Método para resolver problemas com grandezas proporcionais. Direta: a/b = c/d (aumenta uma, aumenta a outra). Inversa: a·b = c·d (aumenta uma, diminui a outra). Na composta, três ou mais grandezas se relacionam ao mesmo tempo — o essencial é identificar se cada uma é direta ou inversa em relação à grandeza procurada.' },
      { nome: 'Matemática financeira', resumo: 'Cobra juros simples (J = C·i·t) e principalmente juros compostos (M = C·(1+i)^t), além de desconto, taxa de juros equivalente e análise de financiamentos. É um dos assuntos mais recorrentes do ENEM, geralmente em contextos de compras, empréstimos e investimentos.' },
      { nome: 'Estatística', resumo: 'Envolve organização e interpretação de dados: construção e leitura de tabelas de frequência, cálculo de médias (média = soma dos valores ÷ quantidade de valores), e principalmente a análise crítica de gráficos (barras, linhas, setores) que aparecem em contextos de reportagens e pesquisas.' },
      { nome: 'Média, mediana e moda', resumo: 'Média aritmética = (soma dos valores) ÷ (quantidade de valores); mediana é o valor central de um conjunto ordenado (ou a média dos dois centrais, se a quantidade for par); moda é o valor mais frequente. O ENEM cobra o cálculo direto e qual medida é mais representativa em cada situação — a mediana, por exemplo, é menos sensível a valores extremos que a média.' },
      { nome: 'Probabilidade', resumo: 'Probabilidade de um evento = casos favoráveis / casos possíveis. Aparece em jogos, sorteios e situações do cotidiano; é importante saber calcular probabilidade de eventos independentes (multiplicação) e complementares (1 − P(evento)).' },
      { nome: 'Funções', resumo: 'Uma função f: A → B relaciona cada elemento de um conjunto (domínio A) a exatamente um elemento de outro (contradomínio B), representada por y = f(x). No ENEM, o foco costuma ser interpretar gráficos de função e associar situações reais (custo, distância, tempo) a uma lei de formação.' },
      { nome: 'Função afim', resumo: 'Função do tipo f(x) = ax + b, cujo gráfico é uma reta. "a" é o coeficiente angular (taxa de variação/inclinação) e "b" é o coeficiente linear (onde a reta corta o eixo y). Muito usada em problemas de custo fixo + custo variável.' },
      { nome: 'Função quadrática', resumo: 'Função do tipo f(x) = ax² + bx + c, com gráfico em parábola. O ENEM costuma pedir o ponto de máximo ou mínimo (vértice) em problemas de otimização, como área máxima de um terreno ou lucro máximo de um produto.' },
      { nome: 'Geometria plana', resumo: 'Estuda figuras em duas dimensões — triângulos, quadriláteros, círculos — e suas propriedades: ângulos, semelhança de triângulos e o Teorema de Pitágoras (a² = b² + c², relacionando os catetos à hipotenusa num triângulo retângulo). É a base para calcular áreas e perímetros, tema recorrente no ENEM em contextos de terrenos e plantas baixas.' },
      { nome: 'Áreas e perímetros', resumo: 'Perímetro é a soma dos lados de uma figura. Áreas principais: retângulo = base × altura; triângulo = (base × altura) ÷ 2; círculo = π × r²; trapézio = ((base maior + base menor) × altura) ÷ 2. Aparecem direto em problemas de reforma, plantação e construção.' },
      { nome: 'Geometria espacial', resumo: 'Trata de figuras tridimensionais — prismas, pirâmides, cilindros, cones, esferas — e suas propriedades. É a base necessária para calcular volumes.' },
      { nome: 'Volumes', resumo: 'Cada sólido tem uma fórmula de volume própria (ex.: cilindro = π·r²·h; prisma = área da base × altura). O ENEM costuma contextualizar em caixas d\u2019água, embalagens e capacidade de recipientes.' },
      { nome: 'Análise de gráficos e tabelas', resumo: 'Habilidade de ler, interpretar e comparar informações apresentadas em gráficos (barras, linhas, setores) e tabelas. É transversal a quase todas as áreas do ENEM, não só matemática, e costuma envolver leitura crítica mais do que cálculo complexo.' },
      { nome: 'Equações e sistemas', resumo: 'Equação do 1º grau: ax + b = 0. Equação do 2º grau: ax² + bx + c = 0, resolvida pela fórmula de Bhaskara: x = (−b ± √(b² − 4ac)) ÷ 2a. Sistemas de equações (duas ou mais incógnitas resolvidas simultaneamente) aparecem em problemas que precisam ser primeiro traduzidos da linguagem natural para a linguagem matemática antes de resolver.' },
      { nome: 'Trigonometria', resumo: 'Num triângulo retângulo: seno = cateto oposto ÷ hipotenusa; cosseno = cateto adjacente ÷ hipotenusa; tangente = cateto oposto ÷ cateto adjacente. Para triângulos quaisquer, usa-se a Lei dos Senos (a/sen A = b/sen B = c/sen C) e a Lei dos Cossenos. Costuma aparecer em problemas de altura, distância e inclinação (rampas, prédios, sombra).' },
    ],
  },
  {
    id: 'redacao',
    emoji: '✍️',
    nome: 'Redação',
    topicos: [
      { nome: 'Estrutura da redação ENEM', resumo: 'A redação do ENEM é um texto dissertativo-argumentativo em prosa, com no mínimo 7 linhas, sobre um tema de ordem social. Segue uma estrutura clássica: introdução (com tese), dois parágrafos de desenvolvimento (cada um com um argumento) e conclusão (com proposta de intervenção).' },
      { nome: 'Introdução e tese', resumo: 'A introdução deve contextualizar o tema e apresentar a tese — o ponto de vista que será defendido e desenvolvido no restante do texto. Uma tese clara já indica ao leitor os argumentos que serão discutidos a seguir.' },
      { nome: 'Desenvolvimento argumentativo', resumo: 'Cada parágrafo de desenvolvimento apresenta um argumento que sustenta a tese, com repertório (dado, citação, fato histórico) como prova, e deve fechar retomando a ideia central do parágrafo.' },
      { nome: 'Repertório sociocultural', resumo: 'É o uso de referências externas ao senso comum — dados, autores, fatos históricos, obras, legislação — para sustentar os argumentos. A banca valoriza um repertório pertinente ao tema e usado de forma produtiva, não apenas citado.' },
      { nome: 'Argumentação', resumo: 'Convencer o leitor da tese defendida, usando estratégias como causa e consequência, comparação, exemplificação e citação de autoridade. Argumentos bem articulados fortalecem a competência 3 da redação.' },
      { nome: 'Coesão e coerência', resumo: 'Coesão é a ligação gramatical entre as partes do texto (uso de conectivos, pronomes, sinônimos); coerência é a lógica interna das ideias, sem contradições. As duas juntas garantem que o texto flua e faça sentido.' },
      { nome: 'Conectivos', resumo: 'Palavras e expressões que ligam ideias e parágrafos (portanto, além disso, por outro lado, dessa forma). O uso variado e adequado de conectivos é um dos critérios avaliados na coesão textual.' },
      { nome: 'Projeto de texto', resumo: 'É o planejamento da redação antes de escrever: definir a tese, os argumentos e a proposta de intervenção. Fazer esse rascunho mental (ou em papel) evita fugir do tema e organiza melhor o tempo de prova.' },
      { nome: 'Proposta de intervenção', resumo: 'Elemento obrigatório da conclusão: quem vai agir, o que vai ser feito, como, por que e qual o efeito esperado — os elementos que a banca do ENEM cobra para dar nota máxima na competência 5.' },
      { nome: 'Competências 1 a 5', resumo: 'A redação do ENEM é avaliada em 5 competências (0 a 200 pontos cada, total 1000): domínio da norma culta, compreensão do tema, seleção de argumentos, coesão/coerência, e proposta de intervenção detalhada.' },
      { nome: 'Temas sociais', resumo: 'O ENEM sempre propõe um tema de relevância social (não é opinião pessoal aleatória) — geralmente ligado a um problema estrutural do Brasil ou do mundo contemporâneo, que exige articulação entre diferentes áreas do conhecimento.' },
      { nome: 'Educação', resumo: 'Tema recorrente: acesso e qualidade do ensino, evasão escolar, desigualdade educacional, tecnologia na educação. Bom repertório: dados do IBGE/INEP, legislação (LDB, Plano Nacional de Educação).' },
      { nome: 'Saúde', resumo: 'Tema recorrente: acesso ao SUS, saúde mental, epidemias, saneamento básico. Bom repertório: dados da OMS, políticas públicas de saúde, exemplos históricos de epidemias.' },
      { nome: 'Meio ambiente', resumo: 'Tema recorrente: desmatamento, mudanças climáticas, consumo consciente, poluição. Bom repertório: acordos internacionais (Acordo de Paris), dados de desmatamento, legislação ambiental.' },
      { nome: 'Tecnologia', resumo: 'Tema recorrente: inclusão digital, inteligência artificial, redes sociais e saúde mental, privacidade de dados. Bom repertório: casos reais de uso/abuso de tecnologia, legislação (LGPD).' },
      { nome: 'Desigualdade social', resumo: 'Tema recorrente: distribuição de renda, racismo estrutural, acesso desigual a direitos básicos. Bom repertório: dados do IBGE, autores que discutem desigualdade no Brasil, histórico de políticas sociais.' },
      { nome: 'Cidadania', resumo: 'Tema recorrente: participação política, direitos e deveres, exercício do voto, movimentos sociais. Bom repertório: Constituição Federal, exemplos de movimentos civis históricos.' },
    ],
  },
  {
    id: 'linguagens',
    emoji: '📖',
    nome: 'Linguagens',
    topicos: [
      { nome: 'Interpretação de texto', resumo: 'Habilidade central da prova de Linguagens: entender o que o texto diz explicitamente, o que sugere nas entrelinhas e qual sua intenção comunicativa. Ler o enunciado com atenção e voltar ao texto para confirmar a resposta evita armadilhas.' },
      { nome: 'Gêneros textuais', resumo: 'Formatos que os textos assumem conforme sua função social — notícia, crônica, poema, propaganda, charge, artigo de opinião. Reconhecer o gênero ajuda a entender a intenção e o contexto de circulação do texto.' },
      { nome: 'Funções da linguagem', resumo: 'Referencial (informar), emotiva (expressar sentimentos), conativa (persuadir), fática (manter contato), metalinguística (falar sobre a própria linguagem) e poética (valorizar a forma). Identificar a função predominante ajuda a interpretar a intenção do texto.' },
      { nome: 'Variação linguística', resumo: 'A língua varia conforme região (regionalismo), classe social, idade, contexto (formal/informal) e época. O ENEM valoriza o reconhecimento dessas variações como parte natural da língua, sem hierarquizá-las como certo ou errado.' },
      { nome: 'Figuras de linguagem', resumo: 'Recursos expressivos como metáfora, metonímia, hipérbole, ironia e antítese, usados para dar mais efeito e sentido ao texto — muito cobrados em interpretação de textos literários e publicitários.' },
      { nome: 'Intertextualidade', resumo: 'Quando um texto dialoga com outro, seja por citação direta, paródia, paráfrase ou alusão. Reconhecer essas referências ajuda a entender camadas extras de sentido, especialmente em textos publicitários e literários.' },
      { nome: 'Linguagem verbal e não verbal', resumo: 'Linguagem verbal usa palavras; não verbal usa imagens, sons, gestos ou símbolos. Muitas questões do ENEM combinam as duas (charges, infográficos, propagandas) e pedem a leitura integrada de ambas.' },
      { nome: 'Argumentação', resumo: 'Na prova objetiva de Linguagens, aparece na análise de textos argumentativos — identificar a tese defendida pelo autor, os argumentos usados e os recursos de persuasão empregados.' },
      { nome: 'Literatura e contexto histórico', resumo: 'Cada movimento literário reflete o contexto histórico e social em que foi produzido. Relacionar características de um texto ao seu período (Barroco, Romantismo, Modernismo etc.) é frequentemente cobrado.' },
      { nome: 'Modernismo', resumo: 'Movimento literário brasileiro iniciado com a Semana de Arte Moderna de 1922, marcado pela ruptura com padrões estéticos anteriores, valorização da cultura nacional e liberdade formal — um dos períodos mais cobrados no ENEM.' },
      { nome: 'Artes e cultura', resumo: 'Questões que relacionam pintura, música, cinema e outras manifestações culturais a seu contexto histórico e social, exigindo leitura crítica de obras de arte como texto.' },
    ],
  },
  {
    id: 'geografia',
    emoji: '🌎',
    nome: 'Geografia',
    topicos: [
      { nome: 'Globalização', resumo: 'Processo de integração econômica, cultural e tecnológica entre países, intensificado a partir do fim do século XX. O ENEM cobra tanto os efeitos positivos (fluxo de informação, comércio) quanto as desigualdades que ela aprofunda entre países centrais e periféricos.' },
      { nome: 'Geopolítica', resumo: 'Estudo das relações de poder entre países e blocos, envolvendo conflitos territoriais, disputas por recursos e alianças internacionais. Frequentemente conectado a notícias atuais no enunciado das questões.' },
      { nome: 'Urbanização', resumo: 'Processo de crescimento das cidades em relação ao campo. No Brasil foi rápido e desordenado, gerando problemas como favelização, déficit habitacional e mobilidade urbana precária — temas centrais nas questões do ENEM.' },
      { nome: 'Industrialização', resumo: 'Processo de desenvolvimento da indústria, que no Brasil ocorreu de forma tardia e concentrada (Sudeste). O ENEM cobra tanto etapas históricas quanto a nova divisão internacional do trabalho, com a industrialização de países asiáticos.' },
      { nome: 'Agropecuária', resumo: 'Estuda a produção agrícola e pecuária, incluindo o agronegócio brasileiro, a agricultura familiar, técnicas de cultivo e seus impactos ambientais e sociais (como o uso de agrotóxicos e a concentração fundiária).' },
      { nome: 'Meio ambiente', resumo: 'Cobre biomas brasileiros, desmatamento, poluição e políticas de conservação. É um dos temas mais transversais da geografia no ENEM, conectando-se a questões de sustentabilidade e economia.' },
      { nome: 'Mudanças climáticas', resumo: 'Alterações no clima global causadas majoritariamente pela ação humana (emissão de gases-estufa). O ENEM costuma relacionar o tema a acordos internacionais e aos impactos desiguais entre países ricos e pobres.' },
      { nome: 'Energia', resumo: 'Estuda as matrizes energéticas (renováveis e não renováveis), com destaque para o papel do Brasil como um dos países com matriz elétrica mais limpa do mundo (hidrelétricas), além de fontes emergentes como eólica e solar.' },
      { nome: 'População e migrações', resumo: 'Analisa a dinâmica demográfica (crescimento, envelhecimento, distribuição) e os fluxos migratórios, internos (êxodo rural) e internacionais (refugiados, imigração econômica), sempre ligando a causas sociais e econômicas.' },
      { nome: 'Questão agrária', resumo: 'Trata da estrutura fundiária brasileira, marcada pela concentração de terras, e dos conflitos agrários — reforma agrária, movimentos sociais do campo (como o MST) e a expansão do agronegócio.' },
      { nome: 'Geografia do Brasil', resumo: 'Cobre a organização do território nacional: regiões, biomas, relevo, clima e as desigualdades regionais de desenvolvimento — base para entender boa parte dos outros temas de geografia do ENEM.' },
    ],
  },
  {
    id: 'historia',
    emoji: '🏛️',
    nome: 'História',
    topicos: [
      { nome: 'Brasil Colônia e escravidão', resumo: 'Período de exploração portuguesa (1500-1822), estruturado pelo trabalho escravo de povos indígenas e, principalmente, africanos. Entender a economia colonial (açúcar, mineração) e a violência da escravidão é base para compreender desigualdades atuais.' },
      { nome: 'Era Vargas', resumo: 'Período de 1930 a 1945 (e depois 1951-1954) em que Getúlio Vargas governou o Brasil, marcado por industrialização, criação de direitos trabalhistas (CLT) e também por um regime autoritário (Estado Novo, 1937-1945).' },
      { nome: 'Ditadura Militar', resumo: 'Regime autoritário no Brasil de 1964 a 1985, marcado por censura, perseguição política, tortura e desaparecimentos, além de um projeto de modernização econômica com forte desigualdade social.' },
      { nome: 'República Velha', resumo: 'Primeiro período republicano brasileiro (1889-1930), marcado pela política do café com leite, o coronelismo e o voto de cabresto — estrutura de poder dominada por elites agrárias.' },
      { nome: 'Redemocratização', resumo: 'Processo de retomada da democracia no Brasil após a ditadura militar, culminando na Constituição de 1988 (a "Constituição Cidadã") e nas primeiras eleições diretas para presidente em 1989.' },
      { nome: 'Revolução Industrial', resumo: 'Processo iniciado na Inglaterra no século XVIII que substituiu o trabalho manual e artesanal pela produção mecanizada, transformando radicalmente as relações de trabalho e dando origem à sociedade industrial moderna.' },
      { nome: 'Imperialismo', resumo: 'Expansão das potências europeias sobre África e Ásia nos séculos XIX e XX, em busca de matérias-primas e mercados consumidores, com forte violência e exploração sobre os povos colonizados — base para entender desigualdades globais atuais.' },
      { nome: 'Segunda Guerra Mundial', resumo: 'Conflito global (1939-1945) entre os Aliados e o Eixo, marcado pelo Holocausto e pelo uso de bombas atômicas, que redesenhou a ordem mundial e deu início à Guerra Fria.' },
      { nome: 'Guerra Fria', resumo: 'Disputa geopolítica e ideológica entre EUA (capitalismo) e URSS (socialismo) de 1945 a 1991, marcada por corrida armamentista, espacial e conflitos indiretos em diversos países, incluindo influência sobre ditaduras na América Latina.' },
      { nome: 'Revolução Francesa', resumo: 'Revolução de 1789 que derrubou a monarquia absolutista na França, disseminando os ideais de liberdade, igualdade e fraternidade que influenciaram movimentos políticos em todo o mundo, incluindo a independência de colônias.' },
    ],
  },
  {
    id: 'filosofia',
    emoji: '🧠',
    nome: 'Filosofia',
    topicos: [
      { nome: 'Ética', resumo: 'Ramo da filosofia que estuda os fundamentos da moral — o que torna uma ação certa ou errada. O ENEM costuma contextualizar dilemas éticos contemporâneos à luz de diferentes correntes filosóficas.' },
      { nome: 'Política e poder', resumo: 'Estuda as formas de organização do poder na sociedade, a legitimidade do Estado e as relações entre governantes e governados, com base em pensadores como Maquiavel, Hobbes, Locke e Rousseau.' },
      { nome: 'Teoria do conhecimento', resumo: 'Investiga como conhecemos o mundo — a origem, a validade e os limites do conhecimento humano, contrapondo correntes como o racionalismo (razão) e o empirismo (experiência).' },
      { nome: 'Platão e Aristóteles', resumo: 'Platão defendia a existência de um "mundo das ideias" perfeito, separado do mundo sensível; Aristóteles, seu aluno, valorizava a observação do mundo real como fonte de conhecimento. Dois pilares da filosofia ocidental, com visões opostas sobre conhecimento e realidade.' },
      { nome: 'Maquiavel', resumo: 'Autor de "O Príncipe", é associado à ideia de que o governante deve priorizar a manutenção do poder e a estabilidade do Estado, mesmo que isso exija ações moralmente questionáveis — origem da expressão "os fins justificam os meios".' },
      { nome: 'Hobbes, Locke e Rousseau', resumo: 'Os três são contratualistas — defendem que o Estado surge de um contrato social — mas divergem: Hobbes vê o estado de natureza como guerra de todos contra todos (justificando um poder forte); Locke defende direitos naturais (vida, liberdade, propriedade); Rousseau valoriza a vontade geral e a igualdade.' },
      { nome: 'Kant', resumo: 'Filósofo que propôs a ética do dever (agir por princípios universais, não por consequências) através do "imperativo categórico", além de uma teoria do conhecimento que une razão e experiência.' },
      { nome: 'Marx', resumo: 'Criador do materialismo histórico e da crítica ao capitalismo, defendia que a luta de classes (entre burguesia e proletariado) é o motor da história e que o modo de produção econômico molda toda a sociedade.' },
      { nome: 'Nietzsche', resumo: 'Filósofo que criticou os valores morais tradicionais (especialmente cristãos), propondo conceitos como "vontade de poder" e a superação do niilismo através da afirmação da vida.' },
    ],
  },
  {
    id: 'sociologia',
    emoji: '👥',
    nome: 'Sociologia',
    topicos: [
      { nome: 'Cultura', resumo: 'Conjunto de valores, crenças, costumes e práticas compartilhados por um grupo social. A sociologia estuda como a cultura é produzida, transmitida e como ela varia entre diferentes sociedades, sem hierarquia entre elas.' },
      { nome: 'Desigualdade social', resumo: 'Estuda as diferenças de acesso a renda, educação, saúde e direitos entre grupos sociais, analisando suas causas estruturais (histórico, econômico, racial) e seus efeitos sobre a mobilidade social.' },
      { nome: 'Trabalho', resumo: 'Analisa as relações de trabalho ao longo da história — da servidão feudal ao trabalho assalariado capitalista — e transformações recentes como a precarização, o trabalho por aplicativo e a automação.' },
      { nome: 'Estado e poder', resumo: 'Estuda as formas de organização e legitimação do poder político na sociedade, incluindo os diferentes tipos de dominação (tradicional, carismática, racional-legal) descritos por Max Weber.' },
      { nome: 'Cidadania', resumo: 'Conjunto de direitos civis, políticos e sociais que garantem a participação do indivíduo na vida pública. A sociologia discute como a cidadania é construída historicamente e nem sempre é plena para todos os grupos.' },
      { nome: 'Movimentos sociais', resumo: 'Ações coletivas organizadas por grupos que reivindicam mudanças sociais, políticas ou econômicas — como o movimento negro, feminista, LGBTQIA+, sindical e o MST. O ENEM costuma cobrar seu papel na conquista de direitos.' },
      { nome: 'Indústria cultural', resumo: 'Conceito criado por Adorno e Horkheimer para descrever a produção em massa de bens culturais (música, cinema, TV) como mercadoria, padronizando o consumo e, segundo os autores, reduzindo o pensamento crítico.' },
      { nome: 'Marx, Durkheim e Weber', resumo: 'Os três fundadores da sociologia moderna: Marx analisa a sociedade pela luta de classes; Durkheim, pela coesão social e fatos sociais; Weber, pela ação social e os sentidos que os indivíduos dão às suas ações.' },
    ],
  },
  {
    id: 'biologia',
    emoji: '🧬',
    nome: 'Biologia',
    topicos: [
      { nome: 'Ecologia', resumo: 'Estuda as relações entre os seres vivos e o ambiente — cadeias alimentares, ciclos de matéria, relações ecológicas (predatismo, mutualismo, competição) e o impacto humano nos ecossistemas.' },
      { nome: 'Cadeias e teias alimentares', resumo: 'Cadeia alimentar mostra a sequência linear de quem come quem (produtor → consumidor → decompositor); teia alimentar é o conjunto de várias cadeias interligadas, mostrando a complexidade real de um ecossistema.' },
      { nome: 'Ciclos biogeoquímicos', resumo: 'Circulação de elementos essenciais à vida (água, carbono, nitrogênio, oxigênio) entre os seres vivos e o ambiente físico. O ciclo do carbono é especialmente cobrado por sua relação com o efeito estufa.' },
      { nome: 'Impactos ambientais', resumo: 'Consequências da ação humana sobre o meio ambiente — desmatamento, poluição, aquecimento global, perda de biodiversidade — geralmente conectadas a discussões sobre sustentabilidade e políticas ambientais.' },
      { nome: 'Genética', resumo: 'Estuda a hereditariedade e a transmissão de características entre gerações, a partir das leis de Mendel (segregação e distribuição independente) e do papel dos genes no DNA.' },
      { nome: 'DNA e RNA', resumo: 'O DNA é a molécula que armazena a informação genética; o RNA atua na leitura e execução dessa informação para produzir proteínas (o chamado dogma central da biologia molecular: DNA → RNA → proteína).' },
      { nome: 'Hereditariedade', resumo: 'Transmissão de características genéticas dos pais para os filhos, estudada através de cruzamentos e proporções (como a clássica 3:1 de Mendel), incluindo heranças dominantes, recessivas e ligadas ao sexo.' },
      { nome: 'Evolução', resumo: 'Teoria de Darwin que explica a diversidade da vida pela seleção natural — indivíduos mais adaptados ao ambiente têm mais chance de sobreviver e se reproduzir, transmitindo suas características às próximas gerações.' },
      { nome: 'Fisiologia humana', resumo: 'Estuda o funcionamento dos sistemas do corpo humano (digestório, respiratório, circulatório, nervoso, endócrino etc.) — um dos temas mais extensos e recorrentes da biologia no ENEM.' },
      { nome: 'Sistema imunológico', resumo: 'Conjunto de células e órgãos que defendem o corpo contra agentes invasores (vírus, bactérias). Ganhou ainda mais destaque no ENEM após a pandemia de covid-19, incluindo o funcionamento de vacinas.' },
      { nome: 'Citologia', resumo: 'Estudo da célula, sua estrutura (membrana, núcleo, organelas) e funções — a unidade básica de todos os seres vivos. Base para entender genética, fisiologia e reprodução.' },
      { nome: 'Metabolismo energético', resumo: 'Processos pelos quais os seres vivos obtêm e utilizam energia, com destaque para a respiração celular (obtenção de energia a partir de nutrientes) e a fotossíntese (produção de matéria orgânica a partir de luz).' },
      { nome: 'Biotecnologia', resumo: 'Uso de organismos vivos ou seus processos para criar produtos e tecnologias — transgênicos, clonagem, terapia gênica, vacinas de RNA mensageiro — sempre acompanhado de discussões éticas no ENEM.' },
      { nome: 'Parasitologia', resumo: 'Estudo dos organismos parasitas e das doenças que causam no ser humano (como malária, esquistossomose e doença de Chagas), geralmente relacionado a saneamento básico e saúde pública.' },
    ],
  },
  {
    id: 'quimica',
    emoji: '⚗️',
    nome: 'Química',
    topicos: [
      { nome: 'Estequiometria', resumo: 'Cálculo das quantidades de reagentes e produtos envolvidos numa reação química, com base nas proporções da equação balanceada — é a "matemática da química" e aparece em quase toda questão que envolve reação.' },
      { nome: 'Soluções e concentração', resumo: 'Estuda misturas homogêneas (soluto + solvente) e as formas de medir sua concentração (g/L, mol/L, porcentagem) — tema recorrente em contextos de medicamentos, poluição da água e produtos do dia a dia.' },
      { nome: 'Química orgânica', resumo: 'Estuda os compostos de carbono, base da vida e de grande parte dos produtos industriais (combustíveis, plásticos, medicamentos, alimentos) — um dos assuntos mais cobrados na química do ENEM.' },
      { nome: 'Funções orgânicas', resumo: 'Grupos de compostos orgânicos com propriedades semelhantes por compartilharem um mesmo grupo funcional — álcoois, ácidos carboxílicos, ésteres, aminas etc. Reconhecer a função a partir da fórmula é uma habilidade central.' },
      { nome: 'Reações orgânicas', resumo: 'Transformações que compostos de carbono sofrem, como combustão, substituição, adição e esterificação — frequentemente contextualizadas em processos industriais e biológicos.' },
      { nome: 'Petróleo e combustíveis', resumo: 'O petróleo é uma mistura de hidrocarbonetos separada por destilação fracionada, originando gasolina, diesel, gás etc. O tema conecta química orgânica a discussões sobre matriz energética e impacto ambiental.' },
      { nome: 'Eletroquímica', resumo: 'Estuda a relação entre reações químicas e corrente elétrica — as pilhas (que geram eletricidade a partir de reações espontâneas) e a eletrólise (que usa eletricidade para forçar uma reação não espontânea).' },
      { nome: 'Pilhas', resumo: 'Dispositivos que convertem energia química em elétrica através de reações de oxirredução espontâneas. Entender os polos (ânodo/cátodo) e o fluxo de elétrons é a base para resolver questões sobre baterias.' },
      { nome: 'Termoquímica', resumo: 'Estuda a energia (calor) liberada ou absorvida nas reações químicas — reações exotérmicas (liberam calor) e endotérmicas (absorvem calor) — com aplicação em combustíveis e processos industriais.' },
      { nome: 'Cinética química', resumo: 'Estuda a velocidade das reações químicas e os fatores que a influenciam (temperatura, concentração, catalisadores, superfície de contato) — muito ligado a exemplos do cotidiano, como conservação de alimentos.' },
      { nome: 'Equilíbrio químico', resumo: 'Estado em que, numa reação reversível, as velocidades da reação direta e inversa se igualam. O Princípio de Le Chatelier explica como o equilíbrio se desloca diante de mudanças de concentração, temperatura ou pressão.' },
      { nome: 'Ácidos e bases', resumo: 'Ácidos liberam H+ em solução aquosa; bases liberam OH-. O ENEM cobra tanto a identificação de ácidos/bases do cotidiano quanto reações de neutralização (ácido + base = sal + água).' },
      { nome: 'pH e pOH', resumo: 'Escala que mede a acidez (pH menor que 7) ou basicidade (pH maior que 7) de uma solução, muito usada em contextos de saúde (pH do sangue), meio ambiente (chuva ácida) e indústria (controle de qualidade).' },
      { nome: 'Química ambiental', resumo: 'Aplica conceitos químicos para entender problemas ambientais — chuva ácida, efeito estufa, poluição da água e do ar, tratamento de esgoto — sempre ligando química a sustentabilidade.' },
    ],
  },
  {
    id: 'fisica',
    emoji: '⚡',
    nome: 'Física',
    topicos: [
      { nome: 'Cinemática', resumo: 'Estuda o movimento dos corpos sem se preocupar com suas causas — velocidade, aceleração, movimento uniforme (MU) e uniformemente variado (MUV) são a base para resolver problemas de deslocamento e tempo.' },
      { nome: 'Leis de Newton', resumo: 'As três leis que fundamentam a mecânica clássica: inércia (um corpo tende a manter seu estado de movimento), F=ma (força resultante é proporcional à aceleração) e ação e reação (toda força gera uma força de reação igual e oposta).' },
      { nome: 'Trabalho e energia', resumo: 'Trabalho é a energia transferida por uma força ao longo de um deslocamento; energia pode ser cinética (movimento) ou potencial (posição). O princípio da conservação de energia é a base para resolver muitos problemas.' },
      { nome: 'Potência', resumo: 'Mede a rapidez com que um trabalho é realizado ou energia é transferida (Potência = Trabalho / tempo) — usada para comparar a eficiência de máquinas, motores e eletrodomésticos.' },
      { nome: 'Hidrostática', resumo: 'Estuda os fluidos em repouso — pressão, empuxo (princípio de Arquimedes, que explica por que objetos flutuam ou afundam) e pressão atmosférica — com aplicações em represas, submarinos e balões.' },
      { nome: 'Calorimetria', resumo: 'Estuda a transferência de calor entre corpos e as mudanças de temperatura e de estado físico (fusão, vaporização), usando conceitos como calor específico e calor latente.' },
      { nome: 'Termodinâmica', resumo: 'Estuda as relações entre calor, trabalho e energia interna dos sistemas, incluindo as leis da termodinâmica — a primeira (conservação de energia) e a segunda (a entropia sempre aumenta em sistemas isolados).' },
      { nome: 'Óptica', resumo: 'Estuda o comportamento da luz — reflexão, refração, formação de imagens em espelhos e lentes — com aplicações em instrumentos ópticos, olho humano e óculos corretivos.' },
      { nome: 'Ondulatória', resumo: 'Estuda as ondas (mecânicas e eletromagnéticas), suas propriedades (frequência, amplitude, comprimento de onda) e fenômenos como reflexão, refração e interferência — base para entender som e luz.' },
      { nome: 'Eletricidade', resumo: 'Estuda cargas elétricas, campo elétrico e corrente elétrica — fundamento para entender desde fenômenos naturais (raios) até o funcionamento de aparelhos eletrônicos do dia a dia.' },
      { nome: 'Eletrodinâmica', resumo: 'Estuda as cargas elétricas em movimento — corrente, tensão, resistência (Lei de Ohm: V=Ri) — base teórica para entender circuitos elétricos.' },
      { nome: 'Circuitos elétricos', resumo: 'Estuda a associação de resistores em série e paralelo, e o comportamento de corrente e tensão em cada configuração — tema muito contextualizado em instalações elétricas residenciais.' },
      { nome: 'Potência elétrica', resumo: 'Mede a energia elétrica consumida ou gerada por unidade de tempo (P=V·i) — a base para entender o consumo de energia de aparelhos elétricos e o cálculo da conta de luz.' },
    ],
  },
];

export const PRIORIDADE = [
  {
    id: 'nivel1',
    nome: 'Nível 1 — dominar primeiro',
    topicos: [
      'Redação',
      'Interpretação de texto',
      'Porcentagem',
      'Razão, proporção e regra de três',
      'Estatística',
      'Geometria',
      'Funções',
      'Probabilidade',
      'Ecologia',
      'Genética',
      'Fisiologia humana',
      'Química orgânica',
      'Estequiometria',
      'Eletricidade',
      'Mecânica',
      'Globalização e geopolítica',
    ],
  },
  {
    id: 'nivel2',
    nome: 'Nível 2 — estudar depois',
    topicos: [
      'Matemática financeira',
      'Geometria espacial',
      'Trigonometria',
      'Brasil República',
      'Urbanização e industrialização',
      'Meio ambiente',
      'Filosofia política e ética',
      'Sociologia — trabalho e desigualdade',
      'Eletroquímica',
      'Termoquímica',
      'Ondulatória',
      'Termodinâmica',
    ],
  },
];
